### ISSUE TITLE
Allow to force 

### ISSUE THREAD

**Issue by fab13n** [vsergeev/u-msgpack-python#26]
I would like to be able to force float serialization to 4-bytes floats rather than 8-bytes doubles. Spontaneously I'd do that by adding an option `single_float=<bool>` to `pack`. Would you be interested by such a pull request, and would you prefer another way to provide this feature?

**Comment by vsergeev** [comment]
Sounds good to me. I'm not sure yet what the best name for the option would be -- perhaps `use_single_float` to be consistent with `use_ordered_dict`.
