### ISSUE TITLE
pack_ext_handler/unpack_ext_handler are not endian aware

### ISSUE THREAD

**Issue by bugfinder** [vsergeev/u-msgpack-python#32]
HI,

pack_ext_handler/unpack_ext_handler break on big-endian platforms like ppc and s390,
so the testcases for these functions fail on all big-endian platforms as they assume little-endian

**Comment by vsergeev** [comment]
Could you point me to the particular test that's failing? As far as I could tell, the library should only treat Ext data is byte arrays, and leave further serialization/deserialization (and accounting for endianness) up to the application.

**Comment by vsergeev** [comment]
Actually, I think I may know what you were referring to. It may have been fixed in commit 16510e9a716f8fc8f0c0daa87269dbf0c7d5ba1f in devel. I'll be making a new release shortly with this fix and timestamp support.

**Comment by vsergeev** [comment]
I've just made a new release v2.5.0, which includes the unit tests fix for big endian platform. Let me know if you run into any more issues.
