### ISSUE TITLE
msgpack deprecating encoding option

### ISSUE THREAD

**Issue by fy0** [vsergeev/u-msgpack-python#41]
Warning in shell:
```
DeprecationWarning: encoding is deprecated, Use raw=False instead.
    return msgpack.loads(data, encoding='utf-8')
```

Offical notes:
https://github.com/msgpack/msgpack-python#deprecating-encoding-option

the option will be removed when msgpack-python 1.0 released.

**Comment by vsergeev** [comment]
I'm not sure I understand the issue. u-msgpack-python does not take an `encoding` option in `loads` or `unpackb`. Are you commenting on the wrong project?

Closing for now. Feel free to re-open if I'm missing something.
