### ISSUE TITLE
use constants instead of calculations

### ISSUE THREAD

**Issue by kapilt** [vsergeev/u-msgpack-python#9]
lots of inline calculations which seem extraneous for size constants.. better to just use constants as ref

**Comment by vsergeev** [comment]
Does this make a difference? Won't the interpreter compile it to bytecode with those calculations substituted by constants? I'm not sure. I'll investigate/benchmark it.

**Comment by vsergeev** [comment]
Performance-wise, I benchmarked this and couldn't find a measurable difference across all four interpreters (on x86 at least). Style-wise, this is an understandable complaint, but personally I don't always like turning every magic number into a named constant. In this case, I prefer the inline calculations, as I find the limits much easier to grok at a glance than jumping around in the code.
